name: stravix_id
description: "STRAVIX.ID - Smart Platform for Business Growth. Digital Business Operating System (SaaS UMKM)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.0

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  lottie: ^3.1.2
  flutter_animate: ^4.5.0

  # Navigation
  go_router: ^14.2.7

  # Local Storage
  shared_preferences: ^2.3.2

  # HTTP & API
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0

  # PDF & Excel
  pdf: ^3.11.1
  excel: ^3.0.0
  printing: ^5.13.3
  path_provider: ^2.1.4
  open_filex: ^4.5.0

  # Charts
  fl_chart: ^0.69.0

  # Image Picker
  image_picker: ^1.1.2

  # Date & Time
  intl: ^0.19.0

  # Utils
  uuid: ^4.5.1
  equatable: ^2.0.5
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.7
  riverpod_generator: ^2.6.2
  freezed: ^2.5.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  # Fonts akan di-load otomatis via google_fonts package
  # Tidak perlu deklarasi font files di sini
